/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param OBJECTID 
 * @param NOMBRE 
 * @param MODALIDAD 
 * @param TIPO 
 * @param MUNICIPIO 
 * @param TELEFONO 
 * @param SIGNATURA 
 * @param OBSERVACIO 
 * @param Estado 
 * @param Est_LLav 
 * @param DIRECCION 
 * @param PLAZAS 
 */
data class AttributesAlojamientosTuristicos (
    val OBJECTID: kotlin.Int? = null,
    val NOMBRE: kotlin.String? = null,
    val MODALIDAD: kotlin.String? = null,
    val TIPO: kotlin.String? = null,
    val MUNICIPIO: kotlin.String? = null,
    val TELEFONO: kotlin.String? = null,
    val SIGNATURA: kotlin.String? = null,
    val OBSERVACIO: kotlin.String? = null,
    val Estado: kotlin.String? = null,
    val Est_LLav: kotlin.Int? = null,
    val DIRECCION: kotlin.String? = null,
    val PLAZAS: kotlin.Int? = null
) {

}

