/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param OBJECTID 
 * @param LATITUD 
 * @param LONGITUD 
 * @param PARADA 
 * @param LINEAS 
 */
data class AttributesParadaGuagua (
    val OBJECTID: kotlin.Int? = null,
    val LATITUD: kotlin.String? = null,
    val LONGITUD: kotlin.String? = null,
    val PARADA: kotlin.String? = null,
    val LINEAS: kotlin.String? = null
) {

}

