/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param OBJECTID 
 * @param Nombre 
 * @param Municipio 
 * @param Telefono 
 * @param Direccion 
 * @param Foto 
 */
data class AttributesParadaTaxi (
    val OBJECTID: kotlin.Int? = null,
    val Nombre: kotlin.String? = null,
    val Municipio: kotlin.String? = null,
    val Telefono: kotlin.Int? = null,
    val Direccion: kotlin.String? = null,
    val Foto: kotlin.String? = null
) {

}

