/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param OBJECTID 
 * @param Linea 
 * @param Recorrido 
 */
data class AttributesLineaGuagua (
    val OBJECTID: kotlin.Int? = null,
    val Linea: kotlin.Int? = null,
    val Recorrido: kotlin.String? = null
) {

}

