/**
 * La Palma Open Data
 * Portal de datos abiertos de la Isla de La Palma
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.beust.klaxon.JsonObject
import com.beust.klaxon.int
import com.beust.klaxon.string


/**
 *
 * @param OBJECTID
 * @param LATITUD
 * @param LONGITUD
 * @param PARADA
 * @param LINEAS
 */
data class AttributesParadaGuagua(
    val OBJECTID: Int? = null,
    val LATITUD: String? = null,
    val LONGITUD: String? = null,
    val PARADA: String? = null,
    val LINEAS: String? = null
){
  constructor(jsonObject: JsonObject?) : this(
      jsonObject?.int("OBJECTID"),
      jsonObject?.string("LATITUD"),
      jsonObject?.string("LONGITUD"),
      jsonObject?.string("PARADA"),
      jsonObject?.string("LINEAS")
  )
}

