/**
 * La Palma Open Data
 * Portal de datos abiertos de la Isla de La Palma
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param attributes
 * @param geometry
 */
data class FeatureParadaGuagua(
    val attributes: AttributesParadaGuagua? = null,
    val geometry: GeometryPoint? = null
)

