/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.AttributesLineaGuagua
import io.swagger.client.models.GeometryPaths

/**
 * 
 * @param attributes 
 * @param geometry 
 */
data class FeatureLineaGuagua (
    val attributes: AttributesLineaGuagua? = null,
    val geometry: GeometryPaths? = null
) {

}

