/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.AttributesParadaTaxi
import io.swagger.client.models.GeometryPoint

/**
 * 
 * @param attributes 
 * @param geometry 
 */
data class FeatureParadaTaxi (
    val attributes: AttributesParadaTaxi? = null,
    val geometry: GeometryPoint? = null
) {

}

