/**
* La Palma Open Data
* Portal de datos abiertos de la Isla de La Palma
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param type 
 * @param alias 
 * @param sqlType 
 * @param length 
 * @param domain 
 * @param defaultValue 
 */
data class Fields (
    val name: kotlin.String? = null,
    val type: kotlin.String? = null,
    val alias: kotlin.String? = null,
    val sqlType: kotlin.String? = null,
    val length: kotlin.Int? = null,
    val domain: kotlin.String? = null,
    val defaultValue: kotlin.String? = null
) {

}

