/**
 * Canary Quake Catalog API
 * Catalog of Earthquakes in the Canary Islands in the last year
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.beust.klaxon.JsonObject
import com.beust.klaxon.int
import com.beust.klaxon.string


/**
 *
 * @param name
 * @param type
 * @param alias
 * @param sqlType
 * @param length
 * @param domain
 * @param defaultValue
 */
data class Fields(
    val name: kotlin.String?,
    val type: kotlin.String?,
    val alias: kotlin.String?,
    val sqlType: kotlin.String?,
    val length: kotlin.Int?,
    val domain: kotlin.String?,
    val defaultValue: kotlin.String?
) {
  constructor(jsonObject: JsonObject) : this(
      jsonObject.string("name"),
      jsonObject.string("type"),
      jsonObject.string("alias"),
      jsonObject.string("sqlType"),
      jsonObject.int("length"),
      jsonObject.string("domain"),
      jsonObject.string("defaultValue")
  )
}

