/**
 * Canary Quake Catalog API
 * Catalog of Earthquakes in the Canary Islands in the last year
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param name
 * @param type
 * @param alias
 * @param sqlType
 * @param length
 * @param domain
 * @param defaultValue
 */
data class Fields(
    val name: String?,
    val type: String?,
    val alias: String?,
    val sqlType: String?,
    val length: Int?,
    val domain: String?,
    val defaultValue: String?
) {
  /*
  constructor(jsonObject: JsonObject) : this(
      jsonObject.string("name"),
      jsonObject.string("type"),
      jsonObject.string("alias"),
      jsonObject.string("sqlType"),
      jsonObject.int("length"),
      jsonObject.string("domain"),
      jsonObject.string("defaultValue")
  )
  */
}

