/**
 * Canary Quake Catalog API
 * Catalog of Earthquakes in the Canary Islands in the last year
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.beust.klaxon.JsonArray
import com.beust.klaxon.JsonObject
import com.beust.klaxon.array

/**
 *
 * @param paths
 */
data class GeometryPaths(
    //val paths: kotlin.Array<GeometryPath>? = null
    private val _paths: JsonArray<JsonArray<JsonArray<Double>>>?
    //val paths: JsonArray<Any>?
    //private val _paths: JsonArray<Any>?

) {


  constructor(jsonObject: JsonObject?) : this(
      jsonObject?.array<JsonArray<JsonArray<Double>>>("paths")
  )

  var paths: Array<Array<Array<Double?>?>?>? = transformGeometryPaths(_paths)


  private fun transformGeometryPaths(
      _paths: JsonArray<JsonArray<JsonArray<Double>>>?
  ): Array<Array<Array<Double?>?>?>? {

    if (_paths != null) {
      val paths = arrayOfNulls<kotlin.Array<kotlin.Array<Double?>?>>(_paths.size)
      for (i in _paths.indices) { // paths
        val _path = _paths[i]
        val path = arrayOfNulls<kotlin.Array<Double?>>(_path.size)
        for (j in _path.indices) { // path
          val _points = _path[j]
          val points = arrayOfNulls<Double>(_points.size)
          for (k in _points.indices) { // points
            points[k] = _points[k]
          }
          path[j] = points
        }
        paths[i] = path
      }
      return paths
    }
    return null
  }


}
