/**
 * Canary Quake Catalog API
 * Catalog of Earthquakes in the Canary Islands in the last year
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.beust.klaxon.JsonObject
import com.beust.klaxon.int


/**
 *
 * @param wkid
 * @param latestWkid
 */
data class SpatialReference(
    val wkid: Int?,
    val latestWkid: Int?
) {
  constructor(jsonObject: JsonObject?) : this(
      jsonObject?.int("wkid"),
      jsonObject?.int("latestWkid")
  )
}

